#!/bin/bash

set -eu
cd "$(dirname "$0")"

mkdir -p generated
rm -rf generated/*

for i in \
  3.10-alpine \
  bash; do
  cp alpine.bats generated/${i}.bats
done

for i in \
  3.10-bullseye \
  3.10-slim \
  bullseye-backports \
  bullseye-slim \
  kali-bleeding-edge \
  kali-rolling \
  ubuntu \
  zsh; do
  cp bullseye.bats generated/${i}.bats
done

for i in \
  centos \
  fedora; do
  cp archlinux.bats generated/${i}.bats
done
